package group_8;

import static java.lang.Integer.parseInt;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gundo Munzhelele
 */
public class playing extends javax.swing.JFrame {

    /**
     * Creates new form playing
     */
    public playing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numbtn1 = new javax.swing.JToggleButton();
        numbtn2 = new javax.swing.JToggleButton();
        numbtn3 = new javax.swing.JToggleButton();
        numbtn4 = new javax.swing.JToggleButton();
        numbtn5 = new javax.swing.JToggleButton();
        numbtn6 = new javax.swing.JToggleButton();
        numbtn7 = new javax.swing.JToggleButton();
        numbtn8 = new javax.swing.JToggleButton();
        numbtn9 = new javax.swing.JToggleButton();
        numbtn10 = new javax.swing.JToggleButton();
        SwappBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        swaps = new javax.swing.JLabel();
        Done = new javax.swing.JButton();
        SkipBtn = new javax.swing.JButton();
        Array = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 48)); // NOI18N
        jLabel1.setText("SORTING ALGORITHMS");

        numbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn1ActionPerformed(evt);
            }
        });

        numbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn2ActionPerformed(evt);
            }
        });

        numbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn3ActionPerformed(evt);
            }
        });

        numbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn4ActionPerformed(evt);
            }
        });

        numbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn5ActionPerformed(evt);
            }
        });

        numbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn6ActionPerformed(evt);
            }
        });

        numbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn7ActionPerformed(evt);
            }
        });

        numbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn8ActionPerformed(evt);
            }
        });

        numbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn9ActionPerformed(evt);
            }
        });

        numbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbtn10ActionPerformed(evt);
            }
        });

        SwappBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SwappBtn.setText("Swapp");
        SwappBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwappBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Number of Swaps :");

        swaps.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        swaps.setText("0");

        Done.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        SkipBtn.setBackground(new java.awt.Color(51, 102, 255));
        SkipBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SkipBtn.setText("Solve using Sorting Algorithms");
        SkipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipBtnActionPerformed(evt);
            }
        });

        Array.setText("Array");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Picture 3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(swaps))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(numbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(numbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(numbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(numbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(numbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(numbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(SwappBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(SkipBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(Done))
            .addComponent(jLabel4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1050, 1050, 1050)
                .addComponent(numbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(numbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Array, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1160, 1160, 1160)
                .addComponent(numbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(numbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(swaps)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(SwappBtn)
                .addGap(60, 60, 60)
                .addComponent(SkipBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(Done))
            .addComponent(jLabel4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(numbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(numbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(Array, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(numbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(numbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn1ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn1ActionPerformed

    private void numbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn2ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn2ActionPerformed

    private void numbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn3ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn3ActionPerformed

    private void numbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn4ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn4ActionPerformed

    private void numbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn5ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn5ActionPerformed

    private void numbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn6ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn6ActionPerformed

    private void numbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn7ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn7ActionPerformed

    private void numbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn8ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn8ActionPerformed

    private void numbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn9ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn9ActionPerformed

    private void numbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbtn10ActionPerformed
        // TODO add your handling code here:
        checkButtonSelection();
    }//GEN-LAST:event_numbtn10ActionPerformed
   //Method to check if 2 buttons are selected 
public void checkButtonSelection() {
    int selectedCount = 0;

    if (numbtn1.isSelected()) selectedCount++;
    if (numbtn2.isSelected()) selectedCount++;
    if (numbtn3.isSelected()) selectedCount++;
    if (numbtn4.isSelected()) selectedCount++;
    if (numbtn5.isSelected()) selectedCount++;
    if (numbtn6.isSelected()) selectedCount++;
    if (numbtn7.isSelected()) selectedCount++;
    if (numbtn8.isSelected()) selectedCount++;
    if (numbtn9.isSelected()) selectedCount++;
    if (numbtn10.isSelected()) selectedCount++;

    // If more than two buttons are selected, disable all buttons
    if (selectedCount >= 2) {
        numbtn1.setEnabled(false);
        numbtn2.setEnabled(false);
        numbtn3.setEnabled(false);
        numbtn4.setEnabled(false);
        numbtn5.setEnabled(false);
        numbtn6.setEnabled(false);
        numbtn7.setEnabled(false);
        numbtn8.setEnabled(false);
        numbtn9.setEnabled(false);
        numbtn10.setEnabled(false);
    }
}



//method to see if only 2 buttons are selected
   private boolean isSelected(JToggleButton one, JToggleButton Two) {
      return one.isSelected() && Two.isSelected();
    }


//method to swapp text
private void swaapTexts(JToggleButton one, JToggleButton two) {
    String temp = one.getText();
    one.setText(two.getText());
    two.setText(temp);
}
//method to reset to default
void Cancel(){
        numbtn1.setEnabled(true);
        numbtn2.setEnabled(true);
        numbtn3.setEnabled(true);
        numbtn4.setEnabled(true);
        numbtn5.setEnabled(true);
        numbtn6.setEnabled(true);
        numbtn7.setEnabled(true);
        numbtn8.setEnabled(true);
        numbtn9.setEnabled(true);
        numbtn10.setEnabled(true);
}

         int Swaps = 0;//initial swapp count
    private void SwappBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwappBtnActionPerformed
    //Create an array of buttons
    JToggleButton[] buttons = {numbtn1, numbtn2, numbtn3, numbtn4, numbtn5, numbtn6, numbtn7, numbtn8, numbtn9, numbtn10};
    JToggleButton firstSelected = null;//create a tooglebutton
    JToggleButton secondSelected = null;
   Swaps++;
    // Find the selected buttons
    for (JToggleButton button : buttons) {//to check which button has been selected
        if (button.isSelected()) {
            if (firstSelected == null) {
                firstSelected = button;
            } else {
                secondSelected = button;
               
                break; // Stop searching after finding two selected buttons
            }
            
        }
    }

    // Swap texts if two buttons are selected
    if (firstSelected != null && secondSelected != null) {
        swaapTexts(firstSelected, secondSelected);
        firstSelected.setSelected(false);
        secondSelected.setSelected(false);
        
    }
    
    Cancel();//reset the buttons to default
    
    swaps.setText(Integer.toString(Swaps));//set text of the swap count
       
    }//GEN-LAST:event_SwappBtnActionPerformed
        boolean IsSorted(){//Method to check if the user entered sorted numbers
               return parseInt(numbtn1.getText()) < parseInt(numbtn2.getText())
                &&    parseInt(numbtn3.getText()) < parseInt(numbtn4.getText())
                &&    parseInt(numbtn5.getText()) < parseInt(numbtn6.getText())
                &&    parseInt(numbtn7.getText()) < parseInt(numbtn8.getText())
                &&    parseInt(numbtn9.getText()) < parseInt(numbtn10.getText());
           }
    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
        if(IsSorted()){//Check to see if the user has sorted the numbers
            JOptionPane.showMessageDialog(null,"Welldone You solved The game with " + swaps.getText() + " ");//display message
        }
        else{
          String input =  JOptionPane.showInputDialog(null, "You did not finish the game "+"\n" +"(Press 1 to solve using algorithms)");//display message and sore the results in a string
            if(input.equalsIgnoreCase("1")){//chek to see if what the user entered matched with the choice they where given
                NextPage next = new NextPage();//create an object of a page called nextpage
                next.array.setText(Array.getText());//set array text to the oage
                next.show();//open nextpage
                this.dispose();//close current page
        }
        }
    }//GEN-LAST:event_DoneActionPerformed

    private void SkipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipBtnActionPerformed
        // TODO add your handling code here:
         NextPage next = new NextPage();//create an object of a page called nextpage
                next.array.setText(Array.getText());//set array text to the oage
                next.show();//open nextpage
                this.dispose();//close current page
    }//GEN-LAST:event_SkipBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Array;
    private javax.swing.JButton Done;
    private javax.swing.JButton SkipBtn;
    private javax.swing.JButton SwappBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JToggleButton numbtn1;
    public static javax.swing.JToggleButton numbtn10;
    public static javax.swing.JToggleButton numbtn2;
    public static javax.swing.JToggleButton numbtn3;
    public static javax.swing.JToggleButton numbtn4;
    public static javax.swing.JToggleButton numbtn5;
    public static javax.swing.JToggleButton numbtn6;
    public static javax.swing.JToggleButton numbtn7;
    public static javax.swing.JToggleButton numbtn8;
    public static javax.swing.JToggleButton numbtn9;
    private javax.swing.JLabel swaps;
    // End of variables declaration//GEN-END:variables
}
